# Generated by Django 5.2.1 on 2025-06-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litrevu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
