# Generated by Django 5.2.1 on 2025-06-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litrevu', '0002_rename_user_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
